#%RAML 1.0
---
title: Data Industries
version: v1
baseUri: https://dataindustries.heroku.com/api
protocols: [ HTTPS ]
mediaType: [ application/json ]

types:

  Services: !include types/Data-Services.raml
  service: !include types/data-service.raml
  fee: !include types/data-fee.raml

/services:
  description: |
    Manage the Data Industries services for business clients. 
    Services includes inspection and verification of 
    environmental matrix and certification of product testing.
  get:
    description: Retrieve the list of services
    responses:
      200:
        body:
          application/json:
            example: !include examples/allServices.json

  post:
    description: Forming new service entity.
    body:
      application/json:
        type: Services
        example: !include examples/createService.json
  
    responses:
      201:
        description: Service created successfully
      500:
        body:
          application/json:
            example: !include examples/createServiceError.json

     
  /{id}:
    get:
      description: Retrieve a single service by Id
      responses:
        200:
          body:
            application/json:
              example: !include examples/serviceId.json
        404:
          description: The service ID doesn't exist
          body:
            application/json:
              example: !include examples/serviceId-error.json
    put:
      description: Updating service entry
      body:
        application/json:
          type: service
          example: |
            {
              "fieldOfTesting": "Microbiology",
              "testFee": 100.55
            }
      responses:
        200:
          description: The service has been updated
          
        404:
          description: The service ID doesn't exist.
          body:
            application/json:
              example: !include examples/serviceId-error.json
    delete:
      description: Deletion of service by Id
      responses:
        204:
          description: The service has been eliminated.
        404:
          description: The service ID doesn't exist.
          body:
            application/json:
              example: !include examples/serviceId-error.json
    

  /fee:
    get:
      description: Listing of services of similar testing fee
      querParameters:
        testFee: integer
      body:
        application/json:
          type: fee
          example: 63.34
        
      responses:
        200:
          body:
            application/json:
              type: object
              example: !include examples/inorganicChem.json
        404:
          description: No service for the fee provided
          body:
            application/json:
              example: !include examples/undefined-fee.json
  

  /test/{category}:
    get:
      description: Listing of service of similar field of testing
      responses:
        200:
          body:
            application/json:
              example: !include examples/similar-fee.json
        400:
          body:
            application/json:
              type:
              example: !include examples/no-serviceFound.json




   
    
    


  