#%RAML 1.0 DataType

type: object
properties:
    customerName:
        description: Name of organization
        type: string
        required: true
    address:
        description: Business address of the company
        type: string
        required: true
    marketInfo:
        description: Main industry sector of the company
        type: string
        required: true
    contact:
        description: Name of contact person
        type: string
        required: true
    email:
        description: Email address of the contact person in the company
        type: string
        required: true
    website:
        description: Website of the company
        type: string
        required: true
    jo:
        description: Services availed in Data Industries
        type: string
        required: true
    joStatus:
        description: General comments about the service ordered
        type: string
        required: true