 #%RAML 1.0 DataType

 type: object
 properties:
    testName:
        description: Name of service
        type: string
        required: true
    testMethod:
        description: Standard method used
        type: string
        required: true
    fieldOfTesting:
        description: branch of scientific category
        type: string
        required: true
    sampleType:
        description: Matrix or media use in laboratory procedure
        type: string
        required: true
    testFee:
        description: Amount of service rendered to client per service
        type: integer
        required: true