#%RAML 1.0 DataType

 type: object
 properties:
    testName:
        description: Name of service
        type?: string
    testMethod:
        description: Standard method used
        type?: string
        
    fieldOfTesting:
        description: branch of scientific category
        type?: string
    sampleType:
        description: Matrix or media use in laboratory procedure
        type?: string
    
    testFee:
        description: Amount of service rendered to client per service
        type?: integer
        